name = 'Informejtycy-theme'
license = 'MIT'
licenselink = 'https://github.com/DawkaWody/Informejtycy/blob/main/src/themes/informejtycy-theme/LICENSE'
description = 'A hugo theme made under Informejtycy project'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/DawkaWody/Informejtycy'

# If you have a running demo of the theme
demosite = 'https://dawkawody.github.io/Informejtycy'

# If the theme has a single author
[author]
  name = 'DawkaWody'
  homepage = 'https://github.com/DawkaWody'
