name = 'Informejtycy-theme'
license = 'MIT'
licenselink = 'https://github.com/DawkaWody/Informejtycy/LICENSE'
description = 'Simple theme made for informejtycy.pl website'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/DawkaWody/Informejtycy'

# If you have a running demo of the theme
demosite = 'https://informejtycy.pl'

# If the theme has multiple authors
authors = [
  {name = 'DawkaWody', homepage = 'https://github.com/DawkaWody'},
  {name = 'patrykniemczyk', homepage = 'Website of author'}
]
