name: Build and remotely deploy site

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
      
      - name: Checkout destination branch
        uses: actions/checkout@v3
        if: github.ref == 'refs/heads/main'
        with:
          ref: built-page # Destination branch name
          path: build-site
        
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.139.3
          extended: true

      - name: Build site
        env:
          TZ: 'Europe/Warsaw'
        run: cd ./src && hugo --minify
      
      - name: Copy all images
        run: cp -Rf ./src/assets/images/ ./src/public/
      
      - name: Copy site to built page branch
        if: github.ref == 'refs/heads/main'
        run: |
          cd ./src
          cp -R public/* ${GITHUB_WORKSPACE}/build-site
          cd ${GITHUB_WORKSPACE}/build-site
          git add .
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Site build no. ${{ github.run_number }} at $(date)"
            git push
          else
            echo "No changes to the output on this push."
          fi
      
      - name: Trigger deploy on remote sever
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: inft
          password: ${{ secrets.REMOTE_PASSWORD }}
          script: |
            cd /home/inft/INFORMEJTYCY-PL
            echo "${{ secrets.REMOTE_PASSWORD }}" | sudo -S bash deploy_static.sh
            echo "${{ secrets.REMOTE_PASSWORD }}" | sudo -S ./.venv/bin/python3 stats_updater/get_stats.py
