name: Build site

on: push

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.139.3
          extended: true

      - name: Build site
        env:
          TZ: 'Europe/Warsaw'
        run: cd ./src && hugo --minify
